# Generated by Django 6.0.3 on 2026-03-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
    ]
