# Generated by Django 6.0.3 on 2026-03-26 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0005_rename_description_categoria_descripcion'),
        ('producto', '0002_alter_producto_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(db_column='categoria', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='categoria.categoria'),
        ),
    ]
