# Generated by Django 6.0.3 on 2026-03-26 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0003_venta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
