# Generated by Django 6.0.3 on 2026-03-26 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categoria', '0004_delete_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='description',
            new_name='descripcion',
        ),
    ]
