# Generated by Django 6.0.3 on 2026-03-26 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='venta',
            table='venta',
        ),
    ]
