# Generated by Django 6.0.3 on 2026-03-26 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
