# Generated by Django 6.0.3 on 2026-03-26 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_table'),
        ('venta', '0005_alter_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(db_column='id_cliente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='cliente.cliente'),
        ),
    ]
